### ISSUE TITLE
new wss4j2.Wss4jSecurityInterceptor does not work with no security actions [SWS-971]

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-ws#1041]
**[Juris Zubkans](https://jira.spring.io/secure/ViewProfile.jspa?name=juris.zubkans)** opened **[SWS-971](https://jira.spring.io/browse/SWS-971?redirect=false)** and commented

I was trying to migrate deprecated Wss4jSecurityInterceptor to new one but can't get it work
when there is no security validation in place.

This is because validationActionsVector is always empty or null.

Here is 2 failing 2 test cases:

    public void testNoSecurity() throws Exception {
    	Wss4jSecurityInterceptor interceptor = new Wss4jSecurityInterceptor();
    	interceptor.setSecurementActions(WSHandlerConstants.USERNAME_TOKEN);
    	interceptor.setSecurementUsername("foo");
    	interceptor.setSecurementPassword("foo");
    	interceptor.setSecurementPasswordType(WSConstants.PW_DIGEST);
    	interceptor.setValidationActions(WSHandlerConstants.NO_SECURITY);
    
    	SoapMessage message = loadSoap11Message("empty-soap.xml");
    	MessageContext context = getSoap11MessageContext(message);
    
    	interceptor.validateMessage(message, context);
    }
    
    public void testNoSecurityAction() throws Exception {
    	Wss4jSecurityInterceptor interceptor = new Wss4jSecurityInterceptor();
    	interceptor.setSecurementActions(WSHandlerConstants.USERNAME_TOKEN);
    	interceptor.setSecurementUsername("foo");
    	interceptor.setSecurementPassword("foo");
    	interceptor.setSecurementPasswordType(WSConstants.PW_DIGEST);
    
    	SoapMessage message = loadSoap11Message("empty-soap.xml");
    	MessageContext context = getSoap11MessageContext(message);
    
    	interceptor.validateMessage(message, context);
    }

because in function
protected void validateMessag...

if (validationActionsVector.contains(WSConstants.NO_SECURITY)) {
return;
}

block is never reached because vector is either empty or null
I suggest  to change this line to

    if (CollectionUtils.isEmpty(validationActionsVector)) {
         return;
    }

---

**Affects:** 2.4.0

**Comment by free-ice** [comment]
Another thing about the implementation is I had setup two WsSecuriontyInterceptors one for signing and one for encryption. This was so I could see the intermediate results and compare what was produced by IBM's DataPower which we replaced. However the encryption interceptor failed because it saw a signed response and could not verify the signature. Not sure if this is an issue in spring-ws or Wss4j.

**Comment by gregturn** [comment]
I'm closing this issue as it was deemed resolved via #1032.

@free-ice If you are still seeing issues, feel free to open a new ticket with details about your build including a possible sample project using Spring Boot.
