### ISSUE TITLE
wsa:to element is not optional [SWS-1031]

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-ws#1100]
**[Leandro](https://jira.spring.io/secure/ViewProfile.jspa?name=leaqui)** opened **[SWS-1031](https://jira.spring.io/browse/SWS-1031?redirect=false)** and commented

The [WS-Addressing 1.0 W3C Recomendation](https://www.w3.org/TR/ws-addr-core/#msgaddrpropsinfoset) says the `wsa:to` property is optional:

```
This OPTIONAL element (whose content is of type xs:anyURI) provides the value for the [destination] property. If this element is NOT present then the value of the [destination] property is "http://www.w3.org/2005/08/addressing/anonymous".
```

But [org.springframework.ws.soap.addressing.client.ActionCallback.getTo()](https://github.com/spring-projects/spring-ws/blob/master/spring-ws-core/src/main/java/org/springframework/ws/soap/addressing/client/ActionCallback.java#L218) initializes the wsa:to property.

And even then, at [AbstractAddressingVersion.addAddressingHeaders()](https://github.com/spring-projects/spring-ws/blob/3b82d4e01246fa7976866a6462e2d1f684fdd613/spring-ws-core/src/main/java/org/springframework/ws/soap/addressing/version/AbstractAddressingVersion.java#L196), sets mustUnderstand = true to element.

So resulting message is:

```xml
<SOAP-ENV:Header xmlns:wsa="http://www.w3.org/2005/08/addressing">
    <wsa:To SOAP-ENV:mustUnderstand="1">https://example.com/ws/bla</wsa:To>
    ...
</SOAP-ENV:Header>
```

The wsa:to property must be optional and if set, it would be nice to have the chance to configure the mustUderestand attribute value.

---

**Affects:** 2.4.2, 3.0.3

**Reference URL:** https://stackoverflow.com/questions/51538667/spring-ws-wsato-element-is-not-optional

**Referenced from:** pull request https://github.com/spring-projects/spring-ws/pull/115

**Comment by MaskeZen** [comment]
How can set the value of the header wsa:To if it is different that the seted in the WebServiceGatewaySupport as the DefaultUri?
