### ISSUE TITLE
Add support for Apache HttpClient 5.0

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-ws#1164]
Current Apache Http Client 4.x is supported however there is also Apache Http Client 5.0 (and I believe 5.1 is in the making), which contains some breaking changes. Might be worthwhile to add support for Http Client 5.0 next to the 4.5. 

Or add some documentation on how to configure the Apache Http Client using the `ClientHttpRequestFactory` abstraction in Spring itself to configure the Apache Http Client, this would save adding additional support into this and use the abstraction from Spring itself instead.

**Comment by zielarz25** [comment]
+1 It becomes even more important now, when spring-mvc 6.x requires Apache Http Client 5.1+, but spring-ws still needs httpclient 4.x, resulting in some projects having two similar dependencies, potentially conflicting ones

**Comment by mdeinum** [comment]
You don't need to use the http client v4, as mentioned you can also use the `ClientHttpRequestFactory` (the infrastructure used by the `RestTemplate`) and you can use any supported version. Maybe that should become the default instead of have different implementation for different clients.

**Comment by gregturn** [comment]
Apparently, there are some official guides for migrating: https://hc.apache.org/httpcomponents-client-5.2.x/migration-guide/index.html

I need to study them to ensure we are properly aligning with their expectations.

**Comment by gregturn** [comment]
@artemptushkin I invite you to track this ticket on our progress towards HttpClient 5 support.

**Comment by gregturn** [comment]
As a reminder, this ticket is aimed at ADDING support for HttpClient 5, not breaking current users presently on HttpClient 4.x.

I will further check what Spring Framework is doing to see whether or not adding such support would dictate deprecating HttpClient 4 support or not.

**Comment by daromnik** [comment]
Hello, is there any news on this issue ?

**Comment by gregturn** [comment]
I did a first cut implementing it, and the code compiled, but the test cases all broke with some mysterious "Stream already closed" exception that I have yet to debug. I'm not sure if it's how I'm using the code, or if it is simply a false expectation in the test cases that needs to be shook out.

**Comment by Facedancer1984** [comment]
Hello.
Are there any updates on this issue?

**Comment by daromnik** [comment]
Hi, is there any news?

**Comment by gregturn** [comment]
BTW, if anyone wants to investigate working up a pull request implements an Apache HttpClient 5.0-based HttpComponentMessageSender, I'm open to contributions!

**Comment by cachescrubber** [comment]
@gregturn Please see and review  #1356.

**Comment by gregturn** [comment]
Thanks @cachescrubber!

Unfortunately, we can't drop any deprecated code in this release, but we're tracking removal on #1321. I added the components you removed back to your commit, and then added an additional polishing commit.

**Comment by artemptushkin** [comment]
@gregturn can you please let me know when `4.0.5` will be released approximately? I tested on the snapshot - all good with me, thank you here

**Comment by artemptushkin** [comment]
@gregturn sorry for pinging, any plans regarding the release 4.0.5? Really waiting it, thank you

**Comment by amalajone** [comment]
Yeah we are waiting for 4.0.5 ws-core

**Comment by Persi** [comment]
@gregturn  As Release 4.0.5 is currently just blocked by a documentation issue, would it be possible to move that issue to next release and create 4.0.5? This is a blocker for migration to Spring Boot 3 for everybody who uses spring-ws with Spring Boot.

**Comment by gregturn** [comment]
This issue has been released via https://github.com/spring-projects/spring-ws/releases/tag/v4.0.5. It should be picked up in the next release of Spring Boot.

**Comment by ammu-n15** [comment]
Can anyone share me the code for HttpComponentsMessageSender with apache http5 support for SSL context and connection pooling

**Comment by maryZil** [comment]
I use version 4.0.10 - its does not work

**Comment by mi9rom** [comment]
Use HttpComponents5MessageSender instead of  HttpComponentsMessageSender

**Comment by maryZil** [comment]
Yes! Thanks.

**Comment by VijayGogineni** [comment]
@mi9rom thanks for the suggestion, what is the import for the HttpComponents5MessageSender? I use springboot version 3. will this HttpComponents5MessageSender work for me?

**Comment by snigdhasasmal07** [comment]
@VijayGogineni  are there any solutions you found for these issue?

**Comment by yuvalom** [comment]
Regarding the "Stream already closed" issue
I have found something interesting in com.sun.xml.messaging.saaj.util.JAXMStreamSource that is eventually being used by spring ws-core.

There is a finally block that closes the stream, and all following requests that reads from the InputStream will be thrown with "Stream already closed" IOException

I hope I am onto something
