### ISSUE TITLE
Security warning about xmlsec 2.2.0

### ISSUE THREAD

**Issue by nytro77** [spring-projects/spring-ws#1210]
Reported by snyk.io

https://snyk.io/vuln/SNYK-JAVA-ORGAPACHESANTUARIO-1655558

Upgrading from 2.2.0 to 2.2.3 seems to be the fix

**Comment by bfold** [comment]
Please note that org.jvnet.staxex:stax-ex:jar:1.7.8 dependency also has several vulnerabilities published on 26 Jul 2021 on snyk.io:

https://security.snyk.io/search?type=any&q=stax-ex

**Comment by gregturn** [comment]
Superceded by #1214.

**Comment by gregturn** [comment]
#1220 has been opened to separately track stax-ex.
