### ISSUE TITLE
Upgrade to Jakarta EE 9

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-ws#1213]
Upgrade any/all dependencies in order to build against Jakarta EE 9's standard APIs.

**Comment by JonasMorrissey** [comment]
> In [84a1b79](https://github.com/spring-projects/spring-ws/commit/84a1b794364115698d67642cef1936e876983ec8) you completely delete the package `org.springframework.ws.soap.security.xwss`. This is a problem for us since we use xwss as the security provider for a webservice. My question is: Why did you delete the package and what is the best migration path?

May I ask how you ended up migrating to Spring 6? Facing the same problem right now 😢

**Comment by eivinhb** [comment]
@JonasMorrissey We have not been able to upgrade to Spring6 or java 17 because of issues in this thread. My comment above is a breaking change we cannot overcome. What we have done in parallell to this issue is work with our soap-ws-users to write a new api on a restful plain http api to get rid off spring-ws as a whole. For us, Spring-ws i broken.

**Comment by eivinhb** [comment]
@gregturn This is still a documenten feature even though it is delete:

https://github.com/spring-projects/spring-ws/blob/v4.0.3/src/main/asciidoctor/security.adoc#using-springcertificatevalidationcallbackhandler

**Comment by gregturn** [comment]
@eivinhb The reason the `xwss` package was removed in Spring WS 4.0 is because XWS Security hasn't had an update since 2008. The core of SOAP may not have changed, but all the surrounding interfaces have. We can't have Spring WS 4.0, based on Jakarta EE 9+, interoperating with XWS Security through older Java EE interfaces.

See https://github.com/spring-projects/spring-ws/issues/1338#issuecomment-1450302665 and https://spring.io/blog/2022/12/02/spring-ws-samples-upgraded-for-spring-boot-3-0 for more details.

**Comment by gregturn** [comment]
> @gregturn This is still a documented feature even though it is deleted: https://github.com/spring-projects/spring-ws/blob/v4.0.3/src/main/asciidoctor/security.adoc#using-springcertificatevalidationcallbackhandler

Thanks @eivinhb. See #1359 to track that cleanup effort.
