### ISSUE TITLE
Support for spring-core 5.3.13 / spring-boot 2.6.1

### ISSUE THREAD

**Issue by zwbear** [spring-projects/spring-ws#1221]
Hello,

Meanwhile, I try to update my project to use spring-boot 2.6.1 which contains an update of spring-core to 5.3.13. Currently I have  some incompatibility problem using spring-test with ApplicationContextRunner(). For example:
```
 new ApplicationContextRunner().withPropertyValues("a=a")
    .run(context -> {
        // tests
});
```
I got an exception like 
```
java.lang.NoSuchMethodError: 'org.springframework.beans.factory.support.BeanDefinitionBuilder org.springframework.beans.factory.support.BeanDefinitionBuilder.rootBeanDefinition(java.lang.Class, java.util.function.Supplier)'
```
Because this method is available since 5.3.9.

Is there a purpose to upgrade the spring-core to 5.3.13?

Thanks,
Zhao

**Comment by gregturn** [comment]
Spring Boot currently supports 2.7 and 3.0. This aligns with Spring Framework 5.3 and 6.0, and thus Spring WS 3.1 and 4.0.

I'm not sure what version of Spring WS you are using, but you'll have to upgrade to one of these to get on proper footing to debug this situation.

**Comment by gregturn** [comment]
I'm closing this issue. Please feel free to open a new one if you continue having issues on the newer version of Spring Boot.
