### ISSUE TITLE
Evaluate Web Services Interceptor Before Spring Security Filter Chain

### ISSUE THREAD

**Issue by tuckeremulls** [spring-projects/spring-ws#1246]
I have a SOAP-based web services application which is leveraging [Spring Web Services (and Spring WS Security)](https://spring.io/projects/spring-ws) as well as [Spring Security](https://spring.io/projects/spring-security). I am using a custom [AbstractWsSecurityInterceptor](https://docs.spring.io/spring-ws/site/spring-ws-security/apidocs/org/springframework/ws/soap/security/AbstractWsSecurityInterceptor.html) to authenticate the incoming requests (using an injected AuthenticationManager) and to add the successful authentications to the SecurityContext. I then have a custom AcessDecisionManager which is using a custom WebSecurityExpressionHandler to validate a certain property from the principal added to the context by the interceptor.

Below is an idea of what my configuration files look like:

SecurityConfig.java:

```
@Getter
@Setter
@Configuration
@RequiredArgsConstructor
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    private final AccessDecisionManager customAccessDecisionManager;

    @Override
    protected void configure(HttpSecurity http) throws Exception {

        http.
                cors()
                .and().csrf().disable()
                .authorizeRequests()
                .accessDecisionManager(customAccessDecisionManager)
                .antMatchers(GET, "/actuator/**").permitAll()
                .anyRequest().access("customAccessMethod()")
                .and().sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);
    }

}

```

WebServiceConfig.java:

```
@EnableWs
@Configuration
@RequiredArgsConstructor
public class WebServiceConfig extends WsConfigurerAdapter {

    private final AuthenticationManager authenticationManager;

    @Bean
    public ServletRegistrationBean<MessageDispatcherServlet> messageDispatcherServlet(ApplicationContext applicationContext) {
        MessageDispatcherServlet servlet = new MessageDispatcherServlet();
        servlet.setApplicationContext(applicationContext);
        servlet.setTransformWsdlLocations(true);
        return new ServletRegistrationBean<>(servlet, "/ws/*");
    }

    ...

    ...


    @Bean
    AbstractWsSecurityInterceptor customAuthenticationInterceptor() {

        return new CustomAuthenticationInterceptor(authenticationManager);
    }

    @Override
    public void addInterceptors(List<EndpointInterceptor> interceptors) {

        interceptors.add(customAuthenticationInterceptor());
    }

}
```

The issue with this setup is that the Spring Security filter chain is evaluated first and fails the authentication because the AccessDecisionManager is evaluated before the request has a chance to enter the custom AbstractWsSecurityInterceptor and place the authentication in the SecurityContext.

Is there any way to evaluate the interceptor and handling of the request on the Web Services and WS Security side of things before it then hits the Spring Security filter chain? Is this a possibility?

Thank you in advance for the help!

**Comment by mdeinum** [comment]
In short no. The `Filter` is part of the Servlet API and the the flow and order of execution is that it first hits the `Filter`, then the `Servlet` which is then invoking the interceptors and endpoint. So it isn't possible to execute the interceptors first because it is technically impossible.

**Comment by gregturn** [comment]
@mdeinum is right. Based upon this, I'm closing this ticket as a change in security management that isn't likely to happen.
