### ISSUE TITLE
Incompatibility to AXIOM 1.3.x+ (Update AXIOM dependency to 1.3.x/1.4.x)

### ISSUE THREAD

**Issue by markieww** [spring-projects/spring-ws#1250]
I was trying to use spring-ws 3.1.3 with axiom 1.4.0.

But at runtime there was `java.lang.NoClassDefFoundError: org/apache/axiom/soap/impl/builder/StAXSOAPModelBuilder`

So did some analyses.

spring-ws still uses axiom 1.2.20 ([pom.xml](https://github.com/spring-projects/spring-ws/blob/main/pom.xml#L91) of spring-ws) 
axiom 1.3.0 is available since 1 Jul 2021 ([git-tag](https://gitbox.apache.org/repos/asf?p=ws-axiom.git;a=commit;h=c5e42e2e2e4b9c39dbcf1d072a1c9fdf53f953a7))
axiom 1.4.0 is available since 14 May 2022 ([git-tag](https://gitbox.apache.org/repos/asf?p=ws-axiom.git;a=commit;h=18605d0f3ae23fcf786f3ba017db613fc7688ad1))

Since axiom 1.3.0 the `StAXSOAPModelBuilder` has been removed regarding their [release notes ](https://ws.apache.org/axiom/release-notes/1.3.0.html)

> The builder implementations and related classes have been removed from the org.apache.axiom.om.impl.builder and org.apache.axiom.soap.impl.builder packages. This includes the StAXBuilder, StAXOMBuilder, XOPAwareStAXOMBuilder, StAXSOAPModelBuilder and MTOMStAXSOAPModelBuilder classes.

**Comment by veithen** [comment]
If you add the `axiom-compat` JAR to the classpath, then you should be able to use the most recent Axiom version with Spring WS 3.1.3.

**Comment by anbusampath** [comment]
related #1264 https://github.com/spring-projects/spring-ws/issues/1264

**Comment by gregturn** [comment]
Duplicates #1264.
