### ISSUE TITLE
Upgrade to xml-bind 4.0.0.

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-ws#1282]

**Comment by anbusampath** [comment]
jakarta.xml.bind-api 4.0.0 uses jakarta namespace. is spring-ws 3.2.0 switching to Jakarata EE 10? I thought 3.2.0 sticks with javax namespace.

**Comment by gregturn** [comment]
Short answer: no.

Jakarta EE 9 is where the jakarta namespace operates. But somehow, this update passed all my tests.

Nevertheless, I need move it back to a pre-Jakarta EE 9 version.

**Comment by gregturn** [comment]
Now I see it. This was a setting only in the `java11` profile. I'll have to fix this (and a couple others!)
