### ISSUE TITLE
Introduce Spring WS BOM

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-ws#1290]
The bom has been configured with a parent:

https://github.com/spring-projects/spring-ws/blob/b67a03dbdd2a152640305d34f2e9bbbab4d422bc/spring-ws-bom/pom.xml#L7-L11

This parent contains dependency management:

https://github.com/spring-projects/spring-ws/blob/b67a03dbdd2a152640305d34f2e9bbbab4d422bc/pom.xml#L131-L166

As a result, the bom's managing the versions of Spring Framework, Spring Security, JUnit, and Jetty. It should only manage the versions of Spring Web Service's own modules.

**Comment by gregturn** [comment]
Based on the complexity arising and being this late, I'm going to withdraw the BOM from Spring WS `4.0` and revisit it later @wilkinsona.

**Comment by gregturn** [comment]
Thanks @mdeinum. I worked through this slightly modified setup and ran it by a couple teammates for review.
