### ISSUE TITLE
Fix broken image links in ref docs.

### ISSUE THREAD

**Issue by mconner** [spring-projects/spring-ws#1328]
what-is-spring-ws.adoc, under Runtime Environment, there's supposed to be an image for 
/spring-projects/spring-ws/raw/main/src/main/asciidoctor/spring-deps.png
It looks like this is supposed to be:
/spring-projects/spring-ws/raw/main/src/main/asciidoctor/**images**/spring-deps.png

Also, even when this is corrected, when viewed in dark mode (switch at top of doc), the arrows in the diagram are not visible..

**Comment by gregturn** [comment]
Confirmed @mconner!

I also verified that inserting "images/" in front of it fixes the issue. Also, turns out this isn't the only image directive.

**Comment by mconner** [comment]
That was fast!  
However, this will not fix the dark-mode issue, correct?

**Comment by gregturn** [comment]
Perhaps open a separate ticket to track that.
