### ISSUE TITLE
When was XwsSecurityInterceptor removed?

### ISSUE THREAD

**Issue by fwilldev** [spring-projects/spring-ws#1330]
Hello everybody,

I noticed that XwsSecurityInterceptor was removed, I cant find it any more in the current release of spring-ws.

When was it removed? The documentation still mentiones the XwsSecurityInterceptor:
https://docs.spring.io/spring-ws/docs/current/reference/html/#security-xws-security-interceptor

Problem is, If I understand right I cant use WSS4JSecurityInterceptor to configure a policy xml file.

Thank in advance!

**Comment by gregturn** [comment]
Yes we dropped it. There are details in https://spring.io/blog/2022/12/02/spring-ws-samples-upgraded-for-spring-boot-3-0. 

That being said, we should update the docs to properly reflect this. If you’d like to make a contribution, we’d appreciate it!

**Comment by fwilldev** [comment]
Thanks for the answer. I will look into it. When i have the time, I will have a look into the documentation and maybe make a contribution.
