### ISSUE TITLE
HttpComponentsMessageSender should support org.apache.hc.client5.http.classic.HttpClient

### ISSUE THREAD

**Issue by francoissey** [spring-projects/spring-ws#1331]
At the moment HttpComponentsMessageSender  support only http 4.x client AKA org.apache.http.client.HttpClient
(https://docs.spring.io/spring-ws/docs/current/api/org/springframework/ws/transport/http/HttpComponentsMessageSender.html)
It would convenient to support http 5.x client org.apache.hc.client5.http.classic.HttpClient

**Comment by gregturn** [comment]
Duplicates #1164

**Comment by francoissey** [comment]
I did try to look it up but I could not find it, thanks a lot :-)
