### ISSUE TITLE
How to use JDK HttpClient with web services?

### ISSUE THREAD

**Issue by turboezh** [spring-projects/spring-ws#1342]
Hi.

I would like to use `java.net.http.HttpClient` (not `HttpURLConnection`) to call remote services and can't figure out how to do it. I didn't find neither implemented `WebServiceMessageSender` nor `ClientHttpRequestFactory` for it as if JDK HttpClient is ignored by Spring.

So I wonder if there any reason to avoid it? Should I use 3d party HTTP client? Or it's just a not-implemented-yet situation?

**Comment by gregturn** [comment]
Resolved.

**Comment by gregturn** [comment]
Check it out @turboezh. We have a new option on the `main` branch.
