### ISSUE TITLE
HttpComponentsMessageSender not supporting HttpClient5

### ISSUE THREAD

**Issue by miriyalajanardhan** [spring-projects/spring-ws#1361]
Upgrading to springboot 3.1, mandates for HttpClient5 and One our SOAP API call which is using HttpComponentsMessageSender  is now not supporting HttpClient5

**Comment by gregturn** [comment]
Check out #1164.

**Comment by miriyalajanardhan** [comment]
that didn't answer any solution or workaround.

**Comment by gregturn** [comment]
We have added support for HttpClient 5 and merged to main. It will be part of the next release of Spring WS, but you can access it today if wanted by simply grabbing the latest snapshot.

**Comment by gregturn** [comment]
#1357 further polishes our support for HttpClient. I suggest you check out `HttpComponents5MessageSender` along with `HttpComponents5ClientFactory` as the factory to create an instance of one.
