### ISSUE TITLE
Spring Boot 3.x.x Compilation Breaks SOAP Marshalling of WSDL Generated POJOs

### ISSUE THREAD

**Issue by matthenry87** [spring-projects/spring-ws#1374]
Spring Boot 3 Eliminates WSDL Generated package-info.class from compiled classes, which is where it sources the SOAP namespace information for the JaxBContext.

To fix, I turned off the incremental compilation on spring-boot-maven-plugin and this allowed the package-info.class to stick around, fixing the issue.

**Comment by gregturn** [comment]
Can you share some more details like your build file?
