### ISSUE TITLE
Add support for Apache HttpClient 5.0

### ISSUE THREAD

**Issue by damizac82** [spring-projects/spring-ws#1386]
Hi, I'm trying to use HttpClient (org.apache.hc.client5.http.classic.HttpClient) with HttpComponentsMessageSender (org.springframework.ws.transport.http) seems to be unsupported. Could you give me some suggestions?

**Comment by gregturn** [comment]
Check out https://github.com/spring-projects/spring-ws/issues/1164 and the related commits, and you'll find the basics amidst our test cases. That should get you going.
