### ISSUE TITLE
Update `SchemaFactoryUtils` to include `jar:nested` in the value of `http://javax.xml.XMLConstants/property/accessExternalSchema`

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-ws#1393]
Spring Boot 3.2 has introduced a new loader implementation for uber jars. Part of this new implementation is a change in the URI scheme for resources within those jars. The scheme is now `jar:nested` whereas it was `jar:file` previously. As reported in https://github.com/spring-projects/spring-boot/issues/38581#issuecomment-1836025373, this change is breaking Spring WS. Can `SchemaFactoryUtils` please be updated in Spring WS 4.0.x to include this new scheme?

**Comment by izeye** [comment]
I created https://github.com/spring-projects/spring-ws/pull/1401 to try to fix this.

**Comment by mario-paniccia** [comment]
having the same issue. Our service upgrade to Spring Boot 3.2  is blocked by this
