### ISSUE TITLE
Getting Caused by: java.lang.NoSuchMethodError: 'void org.apache.xml.security.utils.I18n.init(java.util.ResourceBundle)'

### ISSUE THREAD

**Issue by matteo6b** [spring-projects/spring-ws#1410]
Hello, I have a problem with spring-ws 4.0.10 and with cxf 4.x, I wanted to migrate to Jakarta and I got this error, I was looking to see if it had already been solved in previous versions, I have tried all the possible solutions and I can't find nothing to find the solution that's why I created this issue here I leave the logs

Caused by: java.lang.NoSuchMethodError: 'void org.apache.xml.security.utils.I18n.init(java.util.ResourceBundle)'
org.apache.wss4j.common.crypto.WSProviderConfig.initializeResourceBundles(WSProviderConfig.java:194)
org.apache.wss4j.common.crypto.WSProviderConfig.init(WSProviderConfig.java:69)
	org.apache.wss4j.dom.engine.WSSConfig.init(WSSConfig.java:343)
	org.apache.wss4j.dom.engine.WSSConfig.getNewInstance(WSSConfig.java:365)
	org.apache.wss4j.dom.handler.WSHandler.doSenderAction(WSHandler.java:80)
	org.springframework.ws.soap.security.wss4j2.Wss4jHandler.doSenderAction(Wss4jHandler.java:58)
org.springframework.ws.soap.security.wss4j2.Wss4jSecurityInterceptor.secureMessage(Wss4jSecurityInterceptor.java:628)
org.springframework.ws.soap.security.AbstractWsSecurityInterceptor.handleRequest(AbstractWsSecurityInterceptor.java:206)
org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:576)
org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:539)
	org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:391)
org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:385)

**Comment by corneil** [comment]
@matteo6b Can you please create a small reproducer project with a test case.
