### ISSUE TITLE
Upgrade to commons-collections4 dependency

### ISSUE THREAD

**Issue by tflucker** [spring-projects/spring-ws#1434]
Currently the Artemis-Jakarta-Client dependencies include `commons-collections/commons-collections/3.2.2`.  Would it be possible to update the code so that the `commons-collections4/4.4` dependency is used instead?  This is to address a security vulnerability and pass certain code scans successfully.  Please reach out if additional information is required. Thank you!

**Comment by corneil** [comment]
The commons-collections:3.2.2 dependency is a transitive dependency of a test dependency. 
We cannot exclude this dependency without breaking the jms tests.
