### ISSUE TITLE
OSS Support plan for Version 4.0.X 

### ISSUE THREAD

**Issue by darkly8** [spring-projects/spring-ws#1439]
Hello Team Spring, 

we are using in our project your library with the version 4.0.X. 
As we are using the OSS version, the support will be ended at the 23. November. (https://spring.io/projects/spring-ws#support)

Will there be any updates if a security or vulnerability issues arises for the 4.0.X version?

Do you have a plan, when you want to release the 4.1.0 Version? Will it have the OSS support?

Or do you plan to extend the OSS Support for the 4.0.X version 😃 ?

Kind regards,

Axel

**Comment by corneil** [comment]
The support plan will be extended. We are finalizing details.
