### ISSUE TITLE
Specification and Implementation Details Missing from MANIFEST

### ISSUE THREAD

**Issue by tlh1005** [spring-projects/spring-ws#1440]
Hello,
Latest releases of spring-ws components are published at Maven without version information in the generated MANIFEST.  Below are the content of the spring-ws-core-4.0.11.jar MANIFEST:

Manifest-Version: 1.0
Created-By: Maven JAR Plugin 3.3.0
Build-Jdk-Spec: 17

Was this purposeful or is it due to Maven archive etc. plugins switching to NOT printing this information in the MANIFEST by default?
Thanks,
Troy

**Comment by corneil** [comment]
We've added to main and 4.0.x
