### ISSUE TITLE
marshallSendAndReceivce bug in WebServiceTemplate [SWS-149]

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-ws#303]
**[Martin Koster](https://jira.spring.io/secure/ViewProfile.jspa?name=martin.koster)** opened **[SWS-149](https://jira.spring.io/browse/SWS-149?redirect=false)** and commented

The method "marshalSendAndReceive(String uri, final Object requestPayload)" in class "WebServiceTemplate" calls the wrong overloaded method. The parameter "uri" is not used in this call and will be replaced by the "defaultUri" in the called method.

Wrong:

public Object marshalSendAndReceive(String uri, final Object requestPayload) {
return marshalSendAndReceive(requestPayload, null);
}

Correct:

public Object marshalSendAndReceive(String uri, final Object requestPayload) {
return marshalSendAndReceive(uri, requestPayload, null);
}

---

**Affects:** 1.0 RC2

**Referenced from:** commits https://github.com/spring-projects/spring-ws/commit/24766d2be1ce5ba184af0e4f6300626dd17fb140, https://github.com/spring-projects/spring-ws/commit/001818ab2b8005964ce787d0dc6134bf1a899438

**Comment by NelsonRuddy** [comment]
im facing this issue 
org.springframework.ws.soap.client.SoapFaultClientException: Keine Bank zur BLZ 46062817
 gefunden!

**Comment by NelsonRuddy** [comment]
`public class SoapClient extends WebServiceGatewaySupport {

    @Autowired
    private Jaxb2Marshaller jaxb2Marshaller;

    private WebServiceTemplate template;
    public GetBankResponseType getBank(String endpoint, Object request){
        template = new WebServiceTemplate(jaxb2Marshaller);
        GetBankResponseType response = (GetBankResponseType) template.marshalSendAndReceive(endpoint,request,null);

        return  response;
    }
}`
