### ISSUE TITLE
Contribution: XPathProxy [SWS-157]

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-ws#311]
**[Ray Krueger](https://jira.spring.io/secure/ViewProfile.jspa?name=raykrueger)** opened **[SWS-157](https://jira.spring.io/browse/SWS-157?redirect=false)** and commented

Previously mentioned here:
http://forum.springframework.org/showthread.php?t=41191

I will paraphrase in case the forums ever get changed again :P

I've built something here that might be a nice addition to an xml-tiger package.

Basically, it allows me to access xml like this (from my unit test):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<s:Test xmlns:s="http://www.springframework.org/ws">
  <s:someString>Hello</s:someString>
  <s:anotherString sneaky='boo'>World</s:anotherString>
  <s:booleanExists/>
  <s:booleanTrue>true</s:booleanTrue>
  <s:booleanFalse>false</s:booleanFalse>
  <s:someDouble>123.456</s:someDouble>
  <s:yes>YES</s:yes>
</s:Test>
```

With a proxy generated for an interface that looks like this (again from the unit test):

```
@NamespaceMapping(prefix = "s", uri = "http://www.springframework.org/ws")
public interface Sample {

    @XPathMethod("/s:Test/s:someString")
    String getHello();

    @XPathMethod("/s:Test/s:anotherString[@sneaky=$0]")
    String getWorld(String sneaky);

    @XPathMethod("/s:Test/s:booleanExists")
    Boolean booleanExists();

    @XPathMethod("/s:Test/s:doesNotExist")
    Boolean booleanDoesNotExist();

    @XPathMethod("/s:Test/s:booleanTrue")
    Boolean booleanTrueValue();

    @XPathMethod("/s:Test/s:booleanFalse")
    Boolean booleanFalseValue();

    @XPathMethod("/s:Test/s:yes")
    YesNo yesNo();

    @XPathMethod("/s:Test/s:someDouble")
    Double doubleValue();
}
```

Quick notes...
The "getWorld" method uses an XPathVariableResolver to map the method arguments to xpath variables.

Like the XPathParam stuff in spring-ws, it supports the standard XPath types (String, Boolean, Double, Node, NodeList...). as well as using special Converters.

YesNo in the example above is an enum, a converter is registered with the XPathProxyFactory that allows the conversion of a string to some object.

XPath Booleans are touchy, they are based on existence, not content. This is the default behavior for the XPath proxy as well. Registering a Converter for Booleans though allows s:booleanFalse element above to evaluate to 'false'.

I figured that a spring-xml-tiger package would be a good home for it as it is all JAXP and Annotations. If not, maybe I'll toss it up to sourceforge or googlecode.

I'll attach a zip containing the code. Mind you it's totally "first-draft" quality; the package is "raykrueger.xpathproxy" and has almost no javadoc yet...

---

**Attachments:**
- [xml-tiger.zip](https://jira.spring.io/secure/attachment/12721/xml-tiger.zip) (_12.21 kB_)
- [xml-tiger-2007-11-20.zip](https://jira.spring.io/secure/attachment/13130/xml-tiger-2007-11-20.zip) (_17.11 kB_)
- [xpathproxy.zip](https://jira.spring.io/secure/attachment/12714/xpathproxy.zip) (_9.59 kB_)

**Issue Links:**
- #313 XPath support needs Function and Variable resolvers...
  (_**"depends on"**_)
- #448 Annotation-based version of XPathPayloadEndpointMapping

1 votes, 2 watchers

**Comment by raykrueger** [comment]
I just came across this resurrection of my old XPathProxy idea! Did this make it into Spring in some fashion after all?

**Comment by gregturn** [comment]
@raykrueger I'm afraid not.
